global:
  smtp_smarthost: 'server:25'
  smtp_from: 'alertmanager@mail.com'
  smtp_require_tls: false

route:
  group_by: ['severity']
  group_interval: 5m
  repeat_interval: 5m
  group_wait: 5m
  receiver: 'prometheus-msteams'
  routes:
    - match:
        severity: major
      continue: true
      receiver: 'prometheus-msteams'
    - match:
        severity: major
      receiver: team-a


receivers:
- name: 'team-a'
  email_configs:
  - to: 'email@mail.com'

- name: 'prometheus-msteams'
  webhook_configs:
  - send_resolved: true
    url: 'http://server1:2000/alertmanager'

